name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup., based on https://github.com/edplato/trufflehog-actions-scan'
author: 'traugust'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  githubToken:
    description: 'GitHub Token to access a private repository.'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
outputs:
  numWarnings:
    description: 'the number of warnings, 0 if no warnings were found'
  warningsMarkdown:
    description: 'the warnings rendered as Markdown'
  warningsText:
    description: 'the warnings rendered as plain text'
  warningsJSON:
    description: 'the warnings rendered as JSON'

branding:
  icon: 'shield'  
  color: 'yellow'
