name: 'Trufflehog Actions Scan'
description: 'Scan repository for secrets with basic trufflehog defaults in place for easy setup., based on https://github.com/edplato/trufflehog-actions-scan'
author: 'traugust'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  githubToken:
    description: 'GitHub Token to access a private repository.'
    required: false
  scanArguments:
    description: 'Argument options for scan.'
    required: false
branding:
  icon: 'shield'  
  color: 'yellow'
